-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.13-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table aon2016.divisi
CREATE TABLE IF NOT EXISTS `divisi` (
  `code` int(11) NOT NULL AUTO_INCREMENT,
  `no` int(11) NOT NULL DEFAULT '0',
  `divisi` varchar(50) NOT NULL,
  `posisi` varchar(50) NOT NULL,
  `country` varchar(50) NOT NULL,
  PRIMARY KEY (`code`),
  KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=105 DEFAULT CHARSET=latin1;

-- Dumping data for table aon2016.divisi: ~104 rows (approximately)
/*!40000 ALTER TABLE `divisi` DISABLE KEYS */;
INSERT INTO `divisi` (`code`, `no`, `divisi`, `posisi`, `country`) VALUES
	(1, 1, 'Business Services', 'Balinusa', 'ID'),
	(2, 1, 'Business Services', 'Jawa Tengah', 'ID'),
	(3, 1, 'Business Services', 'Sumatera Tengah', 'ID'),
	(4, 1, 'Business Services', 'Jawa Timur', 'ID'),
	(5, 1, 'Business Services', 'Jakarta', 'ID'),
	(6, 1, 'Business Services', 'Kalimantan', 'ID'),
	(7, 1, 'Business Services', 'Makassar', 'ID'),
	(8, 1, 'Business Services', 'National Office', 'ID'),
	(9, 1, 'Business Services', 'Cibitung', 'ID'),
	(10, 1, 'Business Services', 'Sumatera Utara', 'ID'),
	(11, 1, 'Business Services', 'Papua Maluku', 'ID'),
	(12, 1, 'Business Services', 'Sumatera Selatan', 'ID'),
	(13, 1, 'Business Services', 'Jawa Barat', 'ID'),
	(14, 2, 'Finance & Governance', 'Balinusa', 'ID'),
	(15, 2, 'Finance & Governance', 'Jawa Tengah', 'ID'),
	(16, 2, 'Finance & Governance', 'Sumatera Tengah', 'ID'),
	(17, 2, 'Finance & Governance', 'Cikedokan', 'ID'),
	(18, 2, 'Finance & Governance', 'Jawa Timur', 'ID'),
	(19, 2, 'Finance & Governance', 'Jakarta', 'ID'),
	(20, 2, 'Finance & Governance', 'Kalimantan', 'ID'),
	(21, 2, 'Finance & Governance', 'Makassar', 'ID'),
	(22, 2, 'Finance & Governance', 'National Office', 'ID'),
	(23, 2, 'Finance & Governance', 'Cibitung', 'ID'),
	(24, 2, 'Finance & Governance', 'Sumatera Utara', 'ID'),
	(25, 2, 'Finance & Governance', 'Papua Maluku', 'ID'),
	(26, 2, 'Finance & Governance', 'Sumatera Selatan', 'ID'),
	(27, 2, 'Finance & Governance', 'Jawa Barat', 'ID'),
	(28, 3, 'Human Resources & Information Technology', 'Balinusa', 'ID'),
	(29, 3, 'Human Resources & Information Technology', 'Jawa Tengah', 'ID'),
	(30, 3, 'Human Resources & Information Technology', 'Sumatera Tengah', 'ID'),
	(31, 3, 'Human Resources & Information Technology', 'Cikedokan', 'ID'),
	(32, 3, 'Human Resources & Information Technology', 'Jawa Timur', 'ID'),
	(33, 3, 'Human Resources & Information Technology', 'Jakarta', 'ID'),
	(34, 3, 'Human Resources & Information Technology', 'Kalimantan', 'ID'),
	(35, 3, 'Human Resources & Information Technology', 'Makassar', 'ID'),
	(36, 3, 'Human Resources & Information Technology', 'National Office', 'ID'),
	(37, 3, 'Human Resources & Information Technology', 'Cibitung', 'ID'),
	(38, 3, 'Human Resources & Information Technology', 'Sumatera Utara', 'ID'),
	(39, 3, 'Human Resources & Information Technology', 'Sumatera Selatan', 'ID'),
	(40, 3, 'Human Resources & Information Technology', 'Jawa Barat', 'ID'),
	(41, 4, 'Supply Chain', 'Balinusa', 'ID'),
	(42, 4, 'Supply Chain', 'Jawa Tengah', 'ID'),
	(43, 4, 'Supply Chain', 'Sumatera Tengah', 'ID'),
	(44, 4, 'Supply Chain', 'Cikedokan', 'ID'),
	(45, 4, 'Supply Chain', 'Jawa Timur', 'ID'),
	(46, 4, 'Supply Chain', 'Jakarta', 'ID'),
	(47, 4, 'Supply Chain', 'Makassar', 'ID'),
	(48, 4, 'Supply Chain', 'National Office', 'ID'),
	(49, 4, 'Supply Chain', 'Cibitung', 'ID'),
	(50, 4, 'Supply Chain', 'Sumatera Utara', 'ID'),
	(51, 4, 'Supply Chain', 'Packaging Services', 'ID'),
	(52, 4, 'Supply Chain', 'Sumatera Selatan', 'ID'),
	(53, 4, 'Supply Chain', 'Jawa Barat', 'ID'),
	(54, 5, 'Sales General Trade', 'Balinusa', 'ID'),
	(55, 5, 'Sales General Trade', 'Jawa Tengah', 'ID'),
	(56, 5, 'Sales General Trade', 'Sumatera Tengah', 'ID'),
	(57, 5, 'Sales General Trade', 'Jawa Timur', 'ID'),
	(58, 5, 'Sales General Trade', 'Jakarta', 'ID'),
	(59, 5, 'Sales General Trade', 'Kalimantan', 'ID'),
	(60, 5, 'Sales General Trade', 'Makassar', 'ID'),
	(61, 5, 'Sales General Trade', 'National Office', 'ID'),
	(62, 5, 'Sales General Trade', 'Sumatera Utara', 'ID'),
	(63, 5, 'Sales General Trade', 'Papua Maluku', 'ID'),
	(64, 5, 'Sales General Trade', 'Sumatera Selatan', 'ID'),
	(65, 5, 'Sales General Trade', 'Jawa Barat', 'ID'),
	(66, 6, 'Sales Modern Trade', 'Balinusa', 'ID'),
	(67, 6, 'Sales Modern Trade', 'Jawa Tengah', 'ID'),
	(68, 6, 'Sales Modern Trade', 'Sumatera Tengah', 'ID'),
	(69, 6, 'Sales Modern Trade', 'Jawa Timur', 'ID'),
	(70, 6, 'Sales Modern Trade', 'Jakarta', 'ID'),
	(71, 6, 'Sales Modern Trade', 'Kalimantan', 'ID'),
	(72, 6, 'Sales Modern Trade', 'Makassar', 'ID'),
	(73, 6, 'Sales Modern Trade', 'National Office', 'ID'),
	(74, 6, 'Sales Modern Trade', 'Sumatera Utara', 'ID'),
	(75, 6, 'Sales Modern Trade', 'Sumatera Selatan', 'ID'),
	(76, 6, 'Sales Modern Trade', 'Jawa Barat', 'ID'),
	(77, 7, 'Marketing', 'National Office', 'ID'),
	(78, 8, 'Public Affair & Communication', 'Balinusa', 'ID'),
	(79, 8, 'Public Affair & Communication', 'Jawa Tengah', 'ID'),
	(80, 8, 'Public Affair & Communication', 'Jawa Timur', 'ID'),
	(81, 8, 'Public Affair & Communication', 'Jakarta', 'ID'),
	(82, 8, 'Public Affair & Communication', 'National Office', 'ID'),
	(83, 8, 'Public Affair & Communication', 'Cibitung', 'ID'),
	(84, 8, 'Public Affair & Communication', 'Sumatera Utara', 'ID'),
	(85, 8, 'Public Affair & Communication', 'Jawa Barat', 'ID'),
	(86, 1, 'Corporate', 'Corporate', 'EN'),
	(87, 2, 'Finance', 'Business Services', 'EN'),
	(88, 2, 'Finance', 'Finance & Administration', 'EN'),
	(89, 3, 'Human Resources', 'Human Resources', 'EN'),
	(90, 4, 'Sales ROS', 'Sales ROS', 'EN'),
	(91, 5, 'Sales Northern Region', 'Sales Northern Region', 'EN'),
	(92, 6, 'Sales POM', 'Sales POM', 'EN'),
	(93, 7, 'Marketing & Sales Services', 'Key Accounts', 'EN'),
	(94, 7, 'Marketing & Sales Services', 'Marketing', 'EN'),
	(95, 7, 'Marketing & Sales Services', 'Refrigeration', 'EN'),
	(96, 8, 'Supply Chain', 'Central Warehouse', 'EN'),
	(97, 8, 'Supply Chain', 'Direct Manufacturing', 'EN'),
	(98, 8, 'Supply Chain', 'Distribution', 'EN'),
	(99, 8, 'Supply Chain', 'Indirect Manufacturing', 'EN'),
	(100, 8, 'Supply Chain', 'Logistics', 'EN'),
	(101, 8, 'Supply Chain', 'Maintenance', 'EN'),
	(102, 8, 'Supply Chain', 'Quality Control', 'EN'),
	(103, 8, 'Supply Chain', 'Raw Materials', 'EN'),
	(104, 8, 'Supply Chain', 'Warehouse', 'EN');
/*!40000 ALTER TABLE `divisi` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
